language: ruby
dist: trusty  # work at Ubuntu 14.04 for install Ruby 1.9.3
sudo: false
# https://rubies.travis-ci.org/
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.10
  - 2.5.9
  - 2.6.7
  - 2.7.3
script:
    - rspec spec
