require 'rake'
require 'rspec/core/rake_task'
require 'yaml'
require 'ansible_spec'

properties = AnsibleSpec.get_properties
# {"name"=>"Ansible-Sample-TDD", "hosts"=>["192.168.0.103"], "user"=>"root", "roles"=>["nginx", "mariadb"]}

namespace :serverspec do
  properties.each do |var|
    var["hosts"].each do |host|
      desc "Run serverspec for #{var["name"]}"
      RSpec::Core::RakeTask.new(var["name"].to_sym) do |t|
        puts "Run serverspec for #{var["name"]} to #{host}"
        ENV['TARGET_HOST'] = host
        ENV['TARGET_PRIVATE_KEY'] = '~/.ssh/id_rsa'
        ENV['TARGET_USER'] = var["user"]
        t.pattern = 'roles/{' + var["roles"].join(',') + '}/spec/*_spec.rb'
      end
    end
  end
end

